[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
burry_escrow = "AtUswUKcD5VZf4MdN8rBKeRG9AWPK95PwSHTzhVykrJB"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/geekycoder/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
